// Normalized findings — one per tool
const FINDINGS = [
  { id: 'F-001', scanJobId: 'JOB-9001', projectId: 'NT-CORE', toolName: 'AutoPentestX',
    severity: 'CRITICAL', title: 'VSFTPD 2.3.4 Backdoor',
    description: 'A backdoor was introduced into vsftpd 2.3.4. Triggered by a smiley face in the username, it spawns a root shell on TCP 6200.',
    evidence: 'Connected to 192.168.15.131:21 — sent USER user:) PASS pass — bind shell on :6200 returned uid=0(root).',
    remediation: '1. Immediately upgrade vsftpd to 2.3.6+ from a verified source.\n2. Audit /etc for unknown SUID binaries and recent /tmp activity.\n3. Rotate all credentials reachable from this host.\n4. Add IDS rule for outbound connections from :6200.',
    target: { host: '192.168.15.131', port: 21, service: 'ftp' },
    cve: 'CVE-2011-2523', cvss: 9.8, exploitable: true,
    exploitModule: 'exploit/unix/ftp/vsftpd_234_backdoor',
    status: 'OPEN', isNew: true, firstSeenAt: '12m ago', rawOutputRef: 'job-9001/vsftpd.log' },
  { id: 'F-002', scanJobId: 'JOB-9001', projectId: 'NT-CORE', toolName: 'Guardian-CLI',
    severity: 'HIGH', title: 'Outdated WordPress Version',
    description: 'WordPress 5.4.2 is running with multiple known vulnerabilities including XSS and authenticated SQL injection.',
    evidence: 'GET / → meta name="generator" content="WordPress 5.4.2"',
    remediation: '1. Upgrade WordPress core to 6.x.\n2. Audit and update all active plugins/themes.\n3. Enable automatic minor-version updates.',
    target: { host: 'apds.kku.ac.th', path: '/', service: 'https' },
    cve: null, cvss: 8.1, exploitable: false,
    status: 'CONFIRMED', isNew: false, firstSeenAt: '1d ago' },
  { id: 'F-003', scanJobId: 'JOB-9001', projectId: 'NT-CORE', toolName: 'Caido',
    severity: 'MEDIUM', title: 'Missing Content-Security-Policy Header',
    description: 'No CSP header is returned on the login endpoint. Increases the impact of any XSS that may be discovered.',
    evidence: 'HTTP/1.1 200 OK — Content-Security-Policy header not present.',
    remediation: '1. Add a strict CSP header on all responses.\n2. Start with report-only mode to gather violations.\n3. Tighten to enforcing once telemetry is clean.',
    target: { host: 'dvwa.csalab.app', path: '/login.php', method: 'GET' },
    cve: null, cvss: null, exploitable: false,
    status: 'OPEN', isNew: true, firstSeenAt: '3h ago' },
  { id: 'F-004', scanJobId: 'JOB-9001', projectId: 'NT-CORE', toolName: 'SiriusScan',
    severity: 'CRITICAL', title: 'OpenSSH Remote Code Execution',
    description: 'OpenSSH ssh-agent forwarding is vulnerable to RCE via crafted PKCS#11 module path.',
    evidence: 'banner: SSH-2.0-OpenSSH_8.2p1 — version vulnerable to CVE-2023-38408.',
    remediation: '1. Upgrade OpenSSH to 9.3p2 or later.\n2. Disable agent forwarding (ForwardAgent no) where not required.\n3. Restrict PKCS11Provider via sshd_config.',
    target: { host: '192.168.87.139', port: 22, service: 'ssh' },
    cve: 'CVE-2023-38408', cvss: 9.8, exploitable: true,
    status: 'OPEN', isNew: true, firstSeenAt: '32m ago' },
  { id: 'F-005', scanJobId: 'JOB-9001', projectId: 'NT-CORE', toolName: 'Metlo',
    severity: 'LOW', title: 'New Endpoint Detected — /users',
    description: 'An undocumented endpoint /users was observed in live traffic. The response includes PII (email).',
    evidence: 'PII field exposed: email in response body',
    remediation: '1. Add /users to the OpenAPI spec or remove if unintended.\n2. Mask or omit email unless explicitly required.\n3. Add auth + rate-limit before exposing further.',
    target: { host: 'localhost:6001', path: '/users', method: 'GET' },
    cve: null, cvss: null, exploitable: false,
    status: 'OPEN', isNew: true, firstSeenAt: '45m ago' },
  { id: 'F-006', scanJobId: 'JOB-9001', projectId: 'NT-CORE', toolName: 'VULS',
    severity: 'HIGH', title: 'CVE-2016-1908: OpenSSH X11 Forwarding',
    description: 'OpenSSH allowed remote attackers to bypass intended access restrictions via crafted X11 forwarding data.',
    evidence: 'Installed package openssh-server 7.2p1 matches CVE-2016-1908 advisory.',
    remediation: '1. Upgrade openssh-server to 7.2p2 or later.\n2. Set X11Forwarding no in sshd_config if not required.\n3. Re-run VULS to confirm mitigation.',
    target: { host: '192.168.159.130' },
    cve: 'CVE-2016-1908', cvss: 9.8, exploitable: false,
    status: 'MITIGATED', isNew: false, firstSeenAt: '2d ago' },
];
window.FINDINGS = FINDINGS;
